FROM node:16-slim

RUN  apt-get update \
     && apt-get install -y git openssl --no-install-recommends \
     && apt-get install --reinstall ca-certificates --no-install-recommends -y \
     && rm -rf /var/lib/apt/lists/*
