name: "Build & Publish Docker"

on:
  workflow_call:
    inputs:
      suffix:
        type: string
        required: false
      dockerfile:
        type: string
        required: false
        default: Dockerfile

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=$([[ $GITHUB_REF == refs/tags/v* ]] && echo ${GITHUB_REF#refs/tags/v} || echo 'stable')" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.slim
          push: true
          tags: |
            ghcr.io/moveissimonetti/node-for-build:${{ steps.extract_branch.outputs.branch }}${{ inputs.suffix && format('-{0}', inputs.suffix) || '' }}
