name: Publish Docker image
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
      - 'v\d+'
      - 'v\d+\.\d+'
      - 'v\d+\.\d+\.\d+'

jobs:
  push_to_registry_stable:
    uses: ./.github/workflows/docker.tmpl.yaml
    secrets: inherit

  push_to_registry_slim:
    uses: ./.github/workflows/docker.tmpl.yaml
    with:
      suffix: slim
      dockerfile: Dockerfile.slim
    secrets: inherit

  push_to_registry_gulp_slim:
    uses: ./.github/workflows/docker.tmpl.yaml
    with:
      suffix: gulp-slim
      dockerfile: Dockerfile.gulp-slim
    secrets: inherit
