name: Publish Docker image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
      - 'v\d+'
      - 'v\d+\.\d+'
      - 'v\d+\.\d+\.\d+'

jobs:
  setup:
    name: Discover Dockerfiles
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Find Dockerfiles
        id: set_matrix
        run: |
          matrix_entries="["
          if [ -f "Dockerfile" ]; then
            matrix_entries+="{\"suffix\": \"\", \"dockerfile\": \"Dockerfile\"},"
          fi
          for f in Dockerfile.*; do
            if [ -f "$f" ]; then
              suffix="${f#Dockerfile.}"
              matrix_entries+="{\"suffix\": \"$suffix\", \"dockerfile\": \"$f\"},"
            fi
          done
          matrix_entries="${matrix_entries%,}]"
          echo "matrix=$matrix_entries" >> $GITHUB_OUTPUT

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=$([[ $GITHUB_REF == refs/tags/v* ]] && echo ${GITHUB_REF#refs/tags/v} || echo 'stable')" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/moveissimonetti/node-for-build:${{ steps.extract_branch.outputs.branch }}${{ matrix.suffix && format('-{0}', matrix.suffix) || '' }}
